theme: jekyll-theme-cayman
title: Geazer Selfbot
description: The Geazer (Discord) Selfbot website
logo: https://i.imgur.com/UsrLN7k.gif
image: https://i.imgur.com/UsrLN7k.gif

plugins:
  - jekyll-seo-tag
